apiVersion: v1
kind: Service
metadata:
  name: {{ include "skypos-user.fullname" . }}
  labels:
    {{- include "skypos-user.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8088
      protocol: TCP
      name: http
  selector:
    {{- include "skypos-user.selectorLabels" . | nindent 4 }}
